routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login ');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('offices', 'OfficesController');
Route::resource('users', 'UsersController');
Route::resource('files', 'FilesController');
Route::get('files/{id}email', 'FilesController@email');
Route::resource('online', 'OnlineController');
Route::resource('calculations', 'CalculationsController');
Route::resource('expedientes', 'ExpedienteController');

Route::resource('calculadora', 'CalculadoraController');
Route::post('calculadora', 'CalculadoraController@calculo')->name('calculo.post');


Route::get('mapa', function () {
    return view('formulario.mapa ');
});

Route::resource('directorio', 'DirectorioController');

Route::resource('sucursales', 'SucursalesController');
Route::post('sucursales', 'SucursalesController@sucursal')->name('sucursal.post');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

     public function setPasswordAttribute($value){

        if ( !empty($value)) {
            $this->attributes['password'] = bcrypt($value);
        }
    }

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\User;
use App\Office;
use App\Role;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use PhpParser\Node\Stmt\ElseIf_;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        //

        $idUser = Auth::User()->id;

        $idSucursal = DB::select('SELECT idSucursal, idRol FROM controls WHERE idUser = ?', [$idUser]);
        $idRol = $idSucursal[0]->idRol;
        $idSuc = $idSucursal[0]->idSucursal;



        if ($idRol == 3){

            $users = DB::table('users')
                    ->leftJoin('controls', 'users.id', '=', 'controls.idUser')
                    ->leftJoin('offices', 'controls.idSucursal', '=', 'offices.id')
                    ->join('roles', 'controls.idRol', '=', 'roles.id')
                    ->where('controls.idSucursal', '=', $idSuc)
                    ->get();
        }

        if ($idRol == 1 || $idRol == 2){

            $users = DB::table('users')
                    ->leftJoin('controls', 'users.id', '=', 'controls.idUser')
                    ->leftJoin('offices', 'controls.idSucursal', '=', 'offices.id')
                    ->join('roles', 'controls.idRol', '=', 'roles.id')
                    ->where('users.id', '=', $idUser)
                    ->get();

         }

        if ($idRol == 4 || $idRol == 5){
            $users = DB::table('users')
            ->leftJoin('controls', 'users.id', '=', 'controls.idUser')
            ->leftJoin('offices', 'controls.idSucursal', '=', 'offices.id')
            ->join('roles', 'controls.idRol', '=', 'roles.id')
            ->get();
        }


            return view ('users.index', compact('users'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Id user
        $idUser = Auth::User()->id;
        $idSucursal = DB::select('SELECT idSucursal, idRol FROM controls WHERE idUser = ?', [$idUser]);
        //Id rol
        $idRol = $idSucursal[0]->idRol;
        //Id suc
        $idSuc = $idSucursal[0]->idSucursal;

    // Si es  admin o sup selecciona todos los roles y sucursales
        if($idRol == 4 || $idRol == 5){

            $offices = Office::get();
            $roles = Role::get();

        }
        //Si es gerente selecciona solo su sucursal y roles inferiores
        if( $idRol == 3 ){

            $roles = DB::select('SELECT id, nombre_rol FROM roles WHERE id <= 2 ');
            $offices = DB::select('SELECT id, nombre_suc from offices where id = ?', [$idSuc]);

        }



        return view('users.create', compact('offices', 'roles', 'idUser'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //


        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $idSucursal = $request->idSucursal;
        $idRol = $request->rol;
        //$urlwp->urlwp = $request->urlwp;

        if ($user->save()){


        $idUsers = DB::select('SELECT MAX(id) AS idUser FROM users');

          //INSERTA EN LA TABLA USERSUCURSAL EL ID DE USUARIO Y SUCURSAL
          DB::table('controls')->insert([
            'idSucursal'=> $idSucursal,
            'idUser'=> $idUsers[0]->idUser,
            'idRol'=> $idRol,
            'img_user' => $request->img_user,
            'telefono_user' => $request->telefono_user,
            'facebook_user' => $request->facebook_user,
            'bio_user' => $request->bio_user,
            'whatsapp' => $request->whatsapp,
            'anio_exp' => $request->anio_exp,
            'linkedIn' => $request->linkedIn,
            'bio_user' => $request->bio_user

            ]);


       return redirect('/users');

          }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $users = DB::table('users')
        ->leftJoin('controls', 'users.id', '=', 'controls.idUser')
        ->leftJoin('offices', 'controls.idSucursal', '=', 'offices.id')
        ->join('roles', 'controls.idRol', '=', 'roles.id')
        ->where('users.id', '=', $id)
        ->get();

        $idUser = Auth::User()->id;
        $idSucursal = DB::select('SELECT idSucursal, idRol FROM controls WHERE idUser = ?', [$idUser]);
         //Id rol
         $idRol = $idSucursal[0]->idRol;
         //Id suc
         $idSuc = $idSucursal[0]->idSucursal;


    // Si es  admin o sup selecciona todos los roles y sucursales
        if($idRol == 4 || $idRol == 5){

            $offices = Office::get();
            $roles = Role::get();

        }

        if( $idRol == 3 ){

            $roles = DB::select('SELECT id, nombre_rol FROM roles WHERE id <= 2 ');
            $offices = DB::select('SELECT id, nombre_suc from offices where id = ?', [$idSuc]);

        }
        if( $idRol == 1 || $idRol == 2  ){

            $roles = DB::select('SELECT id, nombre_rol FROM roles WHERE id = ? ', [$idRol]);
            $offices = DB::select('SELECT id, nombre_suc from offices where id = ?', [$idSuc]);

        }

        return view('users.edit', compact('users', 'roles', 'offices'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //



        $user = User::findOrFail($id);

        $user->name = $request->name;


        if ( $request->password != null ){

            $user->password = $request->password;
        }

        $user->save();


        DB::table('controls')
                ->where('idUser', $id)
                ->update([
                    'idSucursal'=> $request->idSucursal,
                    'idRol'=> $request->rol,
                    
                    'telefono_user' => $request->telefono_user,
                    'facebook_user' => $request->facebook_user,
                    'bio_user' => $request->bio_user,
                    'whatsapp' => $request->whatsapp,
                    'anio_exp' => $request->anio_exp,
                    'linkedIn' => $request->linkedIn,
                    'bio_user' => $request->bio_user
                ]);

        return  redirect('/users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        $user = User::findOrFail($id);

        if ( $user ->delete()){
            return redirect('/users');
        }else{
            return response()->json([
                'mensaje'=> 'Error al eliminar el usuario'
            ]);
        }
    }
}

resources/views/users/create.blade.php
@extends('layouts.admin')

@section('content')

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Crear Usuario</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ url('home') }}">Home</a></li>
          <li class="breadcrumb-item active"><a href="{{ url('usuarios') }}">Usuarios</a></li>
            <li class="breadcrumb-item active">Crear usuario</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Nuevo usuario
                </div>
                <div class="card-body">
                <form action="{{ url('users') }}" method="post">
                    @csrf
                    <div class="row">
                        <div class="form-group col-md-5">
                            <label for="name">Nombre </label>
                            <input type="text" name="name" required class="form-control">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="email">Email</label>
                            <input type="email" name="email" required class="form-control">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="password">Password</label>
                            <input type="password" name="password" required class="form-control">
                        </div>
                   </div>

                   <div class="row">
                    <div class="form-group col-md-4">
                       <!--Crear un rol -->
                        <label for="rol">Rol</label>

                        <select name="rol" id="" class="form-control">

                            @foreach ($roles as $rol)

                        <option value="{{ $rol->id }}">{{ $rol->nombre_rol }}</option>

                            @endforeach
                        </select>



                    </div>
                    <div class="form-group col-md-4">
                        <label for="rol">Seleccione una sucursal</label>
                        <select name="idSucursal" id="" required class="form-control">

                        @foreach ($offices as $office)

                    <option value="{{ $office->id  }}">{{ $office->nombre_suc }}</option>

                        @endforeach

                    </select>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="telefono">Teléfono</label>
                        <input type="text" name="telefono_user"  class="form-control">
                    </div>
                    </div>
                    <div class="row">
                    <div class="form-group col-md-3">
                        <label for="whatsapp">WhatsApp</label>
                        <input type="text" name="whatsapp"  class="form-control">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="facebook">Facebook</label>
                        <input type="text" name="facebook_user"  class="form-control">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="linkedIn">LinkedIn</label>
                        <input type="text" name="linkedIn"  class="form-control">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="anio_exp">Años Experiencia</label>
                        <input type="number" name="anio_exp"  class="form-control">
                    </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label for="exampleFormControlTextarea1">Experiencia</label>
                            <textarea class="form-control" name="bio_user" rows="3"></textarea>
                          </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">

                            <input type="file" class="custom-file-input" id="customFile1" name="img_user" >
                            <label class="custom-file-label" for="customFile">Seleccionar archivo</label>

                        </div>
                    </div>
                    <div class="row">
                    <div class="col-md-2 ">
                        <input type="submit" value="Enviar" class="btn btn-success">
                    </div>
                </div>
                </form>

                </div>

            </div>

        </div>

    </div>

</div>
@endsection

resources/views/users/delete.blade.php
<form action="{{ route('users.destroy', $user->id )}}" method="POST" style="display:inline-block;">
    @method('DELETE')
    @csrf
    <button type="submit" class="btn btn-danger">Eliminar</button>
</form>

resources/views/users/edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                Editar usuario
            </div>
            <div class="card-body">
            <form action="{{ route('users.update', $users[0]->idUser ) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="form-group col-md-5">
                    <label for="name">Nombre</label>
                <input type="text" name="name" required class="form-control" value="{{ $users[0]->name}}" >
            </div>
            <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="email" name="email" required class="form-control"  value="{{ $users[0]->email}}">
                </div>
                <div class="form-group col-md-3">
                    <label for="password">Password</label>
                    <input type="password" name="password"  class="form-control">
                </div>
                </div>

                <div class="row">
                 <div class="form-group col-md-4">
                    <label for="rol">Rol</label>
                    <select name="rol" id="" class="form-control">

                        <option  value="{{ $users[0]->idRol }}" >{{ $users[0]->nombre_rol }}</option>
                        @foreach ($roles as $rol)

                        <option  value="{{ $rol->id }}" >{{ $rol->nombre_rol }}</option>

                        @endforeach

                    </select>
                </div>
                <div class="form-group col-md-4">
                    <label for="rol">Seleccione una sucursal</label>
                    <select name="idSucursal" id="" class="form-control">
                      <option value="{{ $users[0]->idSucursal }}">{{ $users[0]->nombre_suc }}</option>
                      @foreach ($offices as $office)
                      <option value="{{ $office->id }}">{{ $office->nombre_suc }}</option>
                      @endforeach



                </select>

            </div>
            <div class="form-group col-md-4">
                <label for="telefono">Teléfono</label>
                <input type="text" name="telefono_user"   value="{{ $users[0]->telefono_user}}" class="form-control">
            </div>
            </div>
            <div class="row">
            <div class="form-group col-md-3">
                <label for="whatsapp">WhatsApp</label>
                <input type="text" name="whatsapp"  value="{{ $users[0]->whatsapp}}" class="form-control">
            </div>
            <div class="form-group col-md-3">
                <label for="facebook">Facebook</label>
                <input type="text" name="facebook_user"  value="{{ $users[0]->facebook_user}}" class="form-control">
            </div>
            <div class="form-group col-md-3">
                <label for="linkedIn">LinkedIn</label>
                <input type="text" name="linkedIn"  value="{{ $users[0]->linkedIn}}" class="form-control">
            </div>
            <div class="form-group col-md-3">
                <label for="anio_exp">Años Experiencia</label>
                <input type="number" name="anio_exp"  value="{{ $users[0]->anio_exp}}" class="form-control">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label for="bio_user">Experiencia</label>
                <textarea class="form-control" name="bio_user" rows="3"  >{{ $users[0]->bio_user }}</textarea>
              </div>
        </div>
            </div>
                <div class="box-tools pull-right ">
                    <input type="submit" value="Enviar" class="btn btn-success">
                </div>
            </form>

            </div>

        </div>

    </div>

</div>

</div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.admin')

@section('content')

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Usuarios</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ url('home') }}">Home</a></li>
            <li class="breadcrumb-item active">Usuarios</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>

<div class="container-fluid spark-screen">
		<div class="row">
			<div class="col-md-12 ">

				<!-- Default box -->
				<div class="box">
					<div class="box-header with-border">


						<div class="box-tools pull-right " >
                        <a href=" {{ url('users/create') }} " class="btn btn-success">Nuevo Usuario</a>
                        </div>

					</div>
					<div class="box-body">
            <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <th>Nombre</th>
                                <th>Email</th>
                                <th>Rol</th>
                                <th>Sucursal</th>
                                <th>Acciones</th>
                            </thead>
                            <tbody>
                                @foreach ($users as $user )
                                    <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>

                                    <td>{{ $user->nombre_rol }}</td>
                                    <td>{{ $user->nombre_suc }}</td>
                                    <td>
                                      <a href="{{ route('directorio.show', $user->name) }}" class="btn btn-info">Landing</a>

                                    <a href="{{ route('users.edit', $user->idUser) }}" class="btn btn-primary">Editar</a>


                                 @include('users.delete', ['user'=>$user])

                                    </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
					</div>
					<!-- /.box-body -->
				</div>
				<!-- /.box -->

			</div>
		</div>
	</div>


@endsection