routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login ');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('offices', 'OfficesController');
Route::resource('users', 'UsersController');
Route::resource('files', 'FilesController');
Route::get('files/{id}email', 'FilesController@email');
Route::resource('online', 'OnlineController');
Route::resource('calculations', 'CalculationsController');
Route::resource('expedientes', 'ExpedienteController');

Route::resource('calculadora', 'CalculadoraController');
Route::post('calculadora', 'CalculadoraController@calculo')->name('calculo.post');


Route::get('mapa', function () {
    return view('formulario.mapa ');
});

Route::resource('directorio', 'DirectorioController');

Route::resource('sucursales', 'SucursalesController');
Route::post('sucursales', 'SucursalesController@sucursal')->name('sucursal.post');

app/Calculation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Calculation extends Model
{
    //
    protected $fillable =  ['limInferior', 'limSuperior', 'cuotaFija', 'porciento'];
}

app/Http/Controllers/CalculationsController.php
<?php

namespace App\Http\Controllers;

use App\Calculation;
use Illuminate\Http\Request;

class CalculationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

      $datos =  Calculation::all();

        return view('calculations.index', compact('datos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        

        return view('calculations.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $datos =  Calculation::all();

        return view('calculations.edit', compact('datos'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/calculations/create.blade.php
@extends('layouts.admin')

@section('content')

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Crear Usuario</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ url('home') }}">Home</a></li>
          <li class="breadcrumb-item active"><a href="{{ url('usuarios') }}">Usuarios</a></li>
            <li class="breadcrumb-item active">Crear usuario</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Nuevo usuario
                </div>
                <div class="card-body">
                <form action="{{ url('calculations') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="name">Nombre</label>
                        <input type="text" name="name" required class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" required class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" required class="form-control">
                    </div>
                    <div class="form-group">
                       <!--Crear un rol -->
                        <label for="rol">Rol</label>
                      
                        <select name="rol" id="" class="form-control">
                           
                            @foreach ($roles as $rol)

                        <option value="{{ $rol->id }}">{{ $rol->nombre }}</option>
                                
                            @endforeach
                        </select>
                        

                   
                    </div>
                    <div class="form-group">
                        <label for="rol">Seleccione una sucursal</label>
                        <select name="idSucursal" id="" class="form-control">

                        @foreach ($offices as $office)

                    <option value="{{ $office->id  }}">{{ $office->nombre }}</option>
                            
                        @endforeach

                    </select>

                    </div>
                    <div class="box-tools pull-right ">
                        <input type="submit" value="Enviar" class="btn btn-success">
                    </div>
                </form>

                </div>

            </div>

        </div>

    </div>

</div>
@endsection

resources/views/calculations/delete.blade.php
<form action="{{ route('calculations.destroy', $dato->id )}}" method="POST" style="display:inline-block;">
    @method('DELETE')
    @csrf
    <button type="submit" class="btn btn-danger">Eliminar</button>
</form>

resources/views/calculations/edit.blade.php
@extends('layouts.admin')


@section('content')


<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Listas de usuarios</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ url('home') }}">Home</a></li>
            <li class="breadcrumb-item active">Solicitudes</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
    

<div class="container-fluid spark-screen">
    <div class="row">
        <div class="col-md-12 ">

            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    
            
                    <div class="box-tools pull-right " >
          <a href=" {{ url('calculations/edit') }} " class="btn btn-success">Guardar </a>
                    </div>
         
                </div>
                <div class="box-body">
        <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <th>Id</th>
                            <th>Límite inferior $</th>
                            <th>Límite superior $</th>
                            <th>Cuota fija $</th>
                            <th>Porciento %</th>
                           
                            
                        </thead>
                        <tbody>
                           
                

                                @foreach ($datos as $dato)
                                <tr>
                                    <td>{{ $dato->id  }}</td>
                                    <td>{{ $dato->limInferior }}</td>
                                    <td>{{ $dato->limSuperior }}</td>
                                    
                                    <td>{{ $dato->cuotaFija }}</td>
                                    <td>{{ $dato->porciento }}</td>
                                    
                                    </tr>
                                @endforeach
                           
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
    </div>

</div>
@endsection

resources/views/calculations/index.blade.php
@extends('layouts.admin')


@section('content')


<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Varibales cálculo de impuestos</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ url('home') }}">Home</a></li>
            <li class="breadcrumb-item active">Tabla</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
    

<div class="container-fluid spark-screen">
    <div class="row">
        <div class="col-md-12 ">

            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    
            
                    <div class="box-tools pull-right " >
         
                    </div>
         
                </div>
                <div class="box-body">
        <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <th>Id</th>
                            <th>Límite inferior $</th>
                            <th>Límite superior $</th>
                            <th>Cuota fija $</th>
                            <th>Porciento %</th>
                            <th>Acciones</th>
                            
                        </thead>
                        <tbody>
                           
                

                                @foreach ($datos as $dato)
                                <tr>
                                    <td>{{ $dato->id  }}</td>
                                    <td>{{ $dato->limInferior }}</td>
                                    <td>{{ $dato->limSuperior }}</td>
                                    
                                    <td>{{ $dato->cuotaFija }}</td>
                                    <td>{{ $dato->porciento }}</td>
                                    <td>
                                
                                        <a href="{{ ('/calculations/'. $dato->id.'/edit/') }}" class="btn btn-primary">Editar</a>
                                      
    
                                     @include('calculations.delete', ['id'=>$dato])
                                   
                                        </td>
                                    </tr>
                                @endforeach
                           
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
    </div>

</div>
@endsection

resources/views/calculations/show.blade.php
@extends('layouts.admin')


@section('content')


<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Calculadora</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ url('home') }}">Home</a></li>
                    <li class="breadcrumb-item active">Calculadora</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>


<div class="container-fluid spark-screen">
    <div class="row">
        <div class="col-md-12 ">

            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">

                </div>
                <div class="box-body">

                   

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
    </div>
</div>


<script>
  
</script>


@STOP