routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login ');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('offices', 'OfficesController');
Route::resource('users', 'UsersController');
Route::resource('files', 'FilesController');
Route::get('files/{id}email', 'FilesController@email');
Route::resource('online', 'OnlineController');
Route::resource('calculations', 'CalculationsController');
Route::resource('expedientes', 'ExpedienteController');

Route::resource('calculadora', 'CalculadoraController');
Route::post('calculadora', 'CalculadoraController@calculo')->name('calculo.post');


Route::get('mapa', function () {
    return view('formulario.mapa ');
});

Route::resource('directorio', 'DirectorioController');

Route::resource('sucursales', 'SucursalesController');
Route::post('sucursales', 'SucursalesController@sucursal')->name('sucursal.post');

resources/views/layouts/partials/contentheader.blade.php
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Starter Page</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Starter Page</li>
                </ol>
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                   
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                 <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    
                </ul>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

resources/views/layouts/partials/controlsidebar.blade.php
<!-- Sidebar -->
<div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href="#" class="d-block">Alexander Pierce</a>
        </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item has-treeview menu-open">
                <a href="#" class="nav-link active">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        Starter Pages
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="#" class="nav-link active">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Active Page</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Inactive Page</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-th"></i>
                    <p>
                        Simple Link
                        <span class="right badge badge-danger">New</span>
                    </p>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>
<!-- /.sidebar -->

resources/views/layouts/partials/docs.blade.php
<div class="card">
    <div class="card-header" id="headingSeven">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven"> <i class="fas fa-folder-plus"></i> Documentos </button>
      </h2>
    </div>
    <div id="collapseSeven" class="collapse" aria-labelledby="headingSeven" data-parent="#accordionExample">
      <div class="card-body">
        <p class="lead"><i class="fas fa-user-check"></i> Documentos del inquilino</p>
        <form action="{{ route('files.update', $document[0]->id) }}" method="POST" enctype="multipart/form-data">
          @csrf
          @method('PUT')
          
           <input type="hidden" name="control"  value="documents">  
       
          <hr>
          <div class="row">
            <div class="col-md-6"> <br>
              <p>Identificación</p>
              <div class="custom-file">
                <input type="file" class="custom-file-input" id="customFile" name="identificacion" >
                <label class="custom-file-label" for="customFile" >Seleccionar archivo</label>
              </div>
            </div>
            <div class="col-md-6"> <br>
              <p>Comprobante Domicilio</p>
              <div class="custom-file">
                <input type="file" class="custom-file-input" id="customFile1" name="domicilio" >
                <label class="custom-file-label" for="customFile">Seleccionar archivo</label>
              </div>
            </div>
            <div class="col-md-6"> <br>
                <p>Comprobante Ingresos</p>
                <div class="custom-file">
                  <input type="file" class="custom-file-input" id="customFile1" name="ingresos" >
                  <label class="custom-file-label" for="customFile">Seleccionar archivo</label>
                </div>
              </div>
          </div>
          <br>
          <button class="btn btn-primary" type="submit" data-toggle="collapse" data-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix"><i class="fas fa-folder-plus"></i> Guardar y continuar</button>
          <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - aquí voy-->
        </form>
      </div>
    </div>
  </div>




<div class="card">
  <div class="card-header" id="headingEight">
    <h2 class="mb-0">
      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseEight" aria-expanded="false" aria-controls="collapseEight"> <i class="fas fa-folder-plus"></i> Documentos Cliente </button>
    </h2>
  </div>
  <div id="collapseEight" class="collapse" aria-labelledby="headingEight" data-parent="#accordionExample">
    <div class="card-body">
      <p class="lead"><i class="fas fa-user-check"></i> Documentos del inquilino</p>
      <form action="" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        
         <input type="hidden" name="control"  value="documents">  
     
        <hr>
        <div class="row">
          <div class="col-md-6"> <br>
            <p>Identificación</p>
            <div class="custom-file">
              <input type="file" class="custom-file-input" id="customFile" name="identificacion" >
              <label class="custom-file-label" for="customFile" >Seleccionar archivo</label>
            </div>
          </div>
          <div class="col-md-6"> <br>
            <p>Comprobante Domicilio</p>
            <div class="custom-file">
              <input type="file" class="custom-file-input" id="customFile1" name="domicilio" >
              <label class="custom-file-label" for="customFile">Seleccionar archivo</label>
            </div>
          </div>
          <div class="col-md-6"> <br>
              <p>Comprobante Ingresos</p>
              <div class="custom-file">
                <input type="file" class="custom-file-input" id="customFile1" name="ingresos" >
                <label class="custom-file-label" for="customFile">Seleccionar archivo</label>
              </div>
            </div>
        </div>
        <br>
        <button class="btn btn-primary" type="submit" data-toggle="collapse" data-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix"><i class="fas fa-folder-plus"></i> Guardar y continuar</button>
        <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - aquí voy-->
      </form>
    </div>
  </div>
</div>

resources/views/layouts/partials/empleo.blade.php
<div class="card">
    <div class="card-header" id="headingTwo">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo"> <i class="fas fa-briefcase"></i> Datos de empleo e ingresos </button>
      </h2>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
        <form action="{{ route('files.update', $jobs[0]->id) }}" method="POST">
          @csrf
          @method('PUT')
          <p class="lead"><i class="fas fa-briefcase"></i> Datos de empleo</p>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="profesion">Profesión oficio o puesto</label>
            <input type="text" class="form-control" name="profesion" value="{{ $jobs[0]->profesion }}" >
          <input type="hidden" name="control"  value="jobs">  
          </div>
            <div class="form-group col-md-6">
              <label class="d-inline-block">Tipo de empleo</label>
              <select class="form-control">
                <option>Seleccione una opción</option>
                <option>Propietario</option>
                <option>Socio</option>
                <option>Empleado</option>
                <option>Comisionista</option>
                <option>Jubilado</option>
              </select>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-4">
              <label>Teléfono</label>
            <input type="tel" class="form-control" name="tel" value="{{ $jobs[0]->tel }}">
            </div>
            <div class="form-group col-md-2">
              <label>Extensión</label>
            <input type="tel" class="form-control"  name="ext" value="{{ $jobs[0]->ext }}">
            </div>
          </div>
          <hr>
          <div class="form-row">
            <div class="form-group col-md-12">
              <label for="empresa">Empresa donde trabaja</label>
            <input type="text" class="form-control" name="empresa" value="{{ $jobs[0]->empresa }}">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-12">
              <label for="calle">Calle</label>
            <input type="text" class="form-control" name="calle" value="{{ $jobs[0]->calle }}">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-4">
              <label for="ext">Número exterior</label>
              <input type="text" class="form-control" name="numExt" value="{{ $jobs[0]->numExt }}">
            </div>
            <div class="form-group col-md-4">
              <label for="int">Número interior</label>
              <input type="text" class="form-control" name="numInt" value="{{ $jobs[0]->numInt }}">
            </div>
            <div class="form-group col-md-4">
              <label for="cp">Código postal</label>
              <input type="text" class="form-control" name="cp" value="{{ $jobs[0]->cp }}">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-4">
              <label for="ext">Colonia</label>
              <input type="text" class="form-control" name="colonia" value="{{ $jobs[0]->colonia }}">
            </div>
            <div class="form-group col-md-4">
              <label for="int">Delegación / Municipio</label>
              <input type="text" class="form-control" name="mun" value="{{ $jobs[0]->mun }}">
            </div>
            <div class="form-group col-md-4">
              <label for="cp">Estado</label>
              <input type="text" class="form-control" name="estado" value="{{ $jobs[0]->estado }}">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-12 col-lg-2">Fecha de ingreso</div>
            <div class="form-group col-4 col-lg-1">
              <label class="d-inline-block" for="dia">Día</label>
              <select class="form-control">
                <option>01</option>
                <option>02</option>
                <option>03</option>
                <option>04</option>
                <option>05</option>
              </select>
            </div>
            <div class="form-group col-4 col-lg-1">
              <label class="d-inline-block" for="dia">Mes</label>
              <select class="form-control">
                <option>01</option>
                <option>02</option>
                <option>03</option>
                <option>04</option>
                <option>05</option>
              </select>
            </div>
            <div class="form-group col-4 col-lg-2">
              <label class="d-inline-block" for="dia">Año</label>
              <select class="form-control">
                <option>2019</option>
                <option>2018</option>
                <option>2017</option>
                <option>2016</option>
                <option>2015</option>
              </select>
            </div>
          </div>
          <hr>
          <p class="lead"><i class="fas fa-user-tie"></i> Jefe inmediato</p>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="">Apellido Paterno</label>
              <input type="text" class="form-control"  name="apellidoPj" value="{{ $jobs[0]->apellidoPj }}">
            </div>
            <div class="form-group col-md-6">
              <label for="">Apellido Materno</label>
              <input type="text" class="form-control"  name="apellidoMj" value="{{ $jobs[0]->apellidoMj }}">
            </div>
          </div>
          <div class="form-group">
            <label for="">Nombre (s)</label>
            <input type="text" class="form-control"  name="nombrej" value="{{ $jobs[0]->nombrej }}">
          </div>
          <div class="form-row">
            <div class="form-group col-md-4">
              <label>Teléfono de oficina</label>
              <input type="tel" class="form-control"  name="telefonoj" value="{{ $jobs[0]->telefonoj }}">
            </div>
            <div class="form-group col-md-2">
              <label>Extensión</label>
              <input type="tel" class="form-control"  name="extj" value="{{ $jobs[0]->extj }}">
            </div>
          </div>
          <hr>
          <p class="lead"><i class="fas fa-dollar-sign"></i> Ingresos</p>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label>Ingreso mensual comprobable</label>
              <div class="input-group mb-2">
                <div class="input-group-prepend">
                  <div class="input-group-text">$</div>
                </div>
                <input type="text" class="form-control"  name="ingresos" value="{{ $jobs[0]->ingresos }}">
              </div>
            </div>
            <div class="form-group col-md-6">
              <label>Ingreso familiar mensual comprobable</label>
              <div class="input-group mb-2">
                <div class="input-group-prepend">
                  <div class="input-group-text">$</div>
                </div>
                <input type="text" class="form-control"  name="ingresoFam" value="{{ $jobs[0]->ingresoFam }}">
              </div>
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-6">
              <label>Número de personas que aportan al ingreso familiar</label>
              <input type="text" class="form-control col-2"  name="numPerIngre" value="{{ $jobs[0]->numPerIngre }}">
            </div>
            <div class="col-md-6">
              <label>Número de personas que dependen de usted</label>
              <input type="text" class="form-control col-2"  name="numPerDep" value="{{ $jobs[0]->numPerDep }}">
            </div>
          </div>
          <br>
          <div class="card">
            <div class="card-header"> <i class="fas fa-exclamation-circle"></i> Llenar sólo en caso de que alguna persona más aporte al ingreso familiar </div>
            <div class="card-body">
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="">Apellido Paterno</label>
                  <input type="text" class="form-control"  name="apellidoPa" value="{{ $jobs[0]->apellidoPa }}">
                </div>
                <div class="form-group col-md-6">
                  <label for="">Apellido Materno</label>
                  <input type="text" class="form-control"  name="apellidoMa" value="{{ $jobs[0]->apellidoMa }}">
                </div>
              </div>
              <div class="form-group">
                <label for="">Nombre (s)</label>
                <input type="text" class="form-control"  name="nombrea" value="{{ $jobs[0]->nombrea }}">
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="">Parentesco</label>
                  <input type="text" class="form-control"  name="parentesco" value="{{ $jobs[0]->parentesco }}">
                </div>
                <div class="form-group col-md-6">
                  <label for="">Teléfono</label>
                  <input type="tel" class="form-control"  name="telefonoA" value="{{ $jobs[0]->telefonoA }}">
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="">Empresa donde trabaja</label>
                  <input type="text" class="form-control"  name="empresaA" value="{{ $jobs[0]->empresaA }}">
                </div>
                <div class="form-group col-md-6">
                  <label>Ingreso mensual comprobable</label>
                  <div class="input-group mb-2">
                    <div class="input-group-prepend">
                      <div class="input-group-text">$</div>
                    </div>
                    <input type="text" class="form-control"  name="ingresoA" value="{{ $jobs[0]->ingresoA }}">
                  </div>
                </div>
              </div>
            </div>
          </div>
       
        <br>
        <button class="btn btn-primary" type="sumbmit" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree"><i class="fas fa-check"></i> Guardar y continuar</button>
      </div>
    </form>
    </div>
  </div>

resources/views/layouts/partials/footer.blade.php
 <!-- Main Footer -->
 <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

resources/views/layouts/partials/htmlheader.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Póliza de Rentas</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ asset('img/favicon.ico') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{ asset('plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
    <!-- summernote -->
    <link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('dist/css/lightbox.css') }}">




    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
  </head>

resources/views/layouts/partials/referencias.blade.php
<div class="card">
    <div class="card-header" id="headingThree">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree"> <i class="fas fa-check-square"></i> Referencias </button>
      </h2>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
      <div class="card-body">
        <form action="{{ route('files.update', $ref[0]->id) }}" method="POST">
          @csrf
          @method('PUT')
          <input type="hidden" name="control"  value="references">  
        <p class="lead"><i class="fas fa-user-friends"></i> Referencias personales</p>
        <p><i class="fas fa-user-check"></i> <small class="text-muted">Referencia personal 1</small></p>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="">Apellido Paterno</label>
            <input type="text" class="form-control" name="apellidoPr1" value="{{ $ref[0]->apellidoPr1 }}">
          </div>
          <div class="form-group col-md-6">
            <label for="">Apellido Materno</label>
            <input type="text" class="form-control" name="apellidoMr1" value="{{ $ref[0]->apellidoMr1 }}">
          </div>
        </div>
        <div class="form-group">
          <label for="">Nombre (s)</label>
          <input type="text" class="form-control" name="nombrer1" value="{{ $ref[0]->nombrer1 }}">
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label>Relación</label>
            <input type="text" class="form-control" name="relacionr1" value="{{ $ref[0]->relacionr1 }}">
          </div>
          <div class="form-group col-md-6">
            <label>Teléfono</label>
            <input type="tel" class="form-control" name="telefonor1" value="{{ $ref[0]->telefonor1 }}">
          </div>
        </div>
        <hr>
        <p><i class="fas fa-user-check"></i> <small class="text-muted">Referencia personal 2</small></p>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="">Apellido Paterno</label>
            <input type="text" class="form-control" name="apellidoPr2" value="{{ $ref[0]->apellidoPr2 }}">
          </div>
          <div class="form-group col-md-6">
            <label for="">Apellido Materno</label>
            <input type="text" class="form-control" name="apellidoMr2" value="{{ $ref[0]->apellidoMr2 }}">
          </div>
        </div>
        <div class="form-group">
          <label for="">Nombre (s)</label>
          <input type="text" class="form-control" name="nombrer2" value="{{ $ref[0]->nombrer2 }}">
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label>Relación</label>
            <input type="text" class="form-control" name="relacionr2" value="{{ $ref[0]->relacionr2 }}">
          </div>
          <div class="form-group col-md-6">
            <label>Teléfono</label>
            <input type="tel" class="form-control" name="telefonor2" value="{{ $ref[0]->telefonor2 }}">
          </div>
        </div>
        <hr>
        <p class="lead"><i class="fas fa-user-friends"></i> Referencias familiares</p>
        <p><i class="fas fa-user-check"></i> <small class="text-muted">Referencia familiar 1</small></p>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="">Apellido Paterno</label>
            <input type="text" class="form-control" name="apellidoPf1" value="{{ $ref[0]->apellidoPf1 }}">
          </div>
          <div class="form-group col-md-6">
            <label for="">Apellido Materno</label>
            <input type="text" class="form-control" name="apellidoMf1" value="{{ $ref[0]->apellidoMf1 }}">
          </div>
        </div>
        <div class="form-group">
          <label for="">Nombre (s)</label>
          <input type="text" class="form-control" name="nombref1" value="{{ $ref[0]->nombref1 }}">
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label>Relación</label>
            <input type="text" class="form-control" name="relacionf1" value="{{ $ref[0]->relacionf1 }}">
          </div>
          <div class="form-group col-md-6">
            <label>Teléfono</label>
            <input type="tel" class="form-control" name="telefonof1" value="{{ $ref[0]->telefonof1 }}">
          </div>
        </div>
        <hr>
        <p><i class="fas fa-user-check"></i> <small class="text-muted">Referencia familiar 2</small></p>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="">Apellido Paterno</label>
            <input type="text" class="form-control" name="apellidoPf2" value="{{ $ref[0]->apellidoPf2 }}">
          </div>
          <div class="form-group col-md-6">
            <label for="">Apellido Materno</label>
            <input type="text" class="form-control" name="apellidoMf2" value="{{ $ref[0]->apellidoMf2 }}">
          </div>
        </div>
        <div class="form-group">
          <label for="">Nombre (s)</label>
          <input type="text" class="form-control" name="nombref2" value="{{ $ref[0]->nombref2 }}">
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label>Relación</label>
            <input type="text" class="form-control" name="relacionf2" value="{{ $ref[0]->relacionf2 }}">
          </div>
          <div class="form-group col-md-6">
            <label>Teléfono</label>
            <input type="tel" class="form-control" name="telefonof2" value="{{ $ref[0]->telefonof2 }}">
          </div>
        </div>
        <button class="btn btn-primary" type="submit" data-toggle="collapse" data-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix"><i class="fas fa-check"></i> Guardar y continuar</button>
      </form>
      </div>
    </div>
  </div>

resources/views/layouts/partials/scripts.blade.php
<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('plugins/sparklines/sparkline.js') }}"></script>

<!-- jQuery Knob Chart -->
<script src="{{ asset('plugins/jquery-knob/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('dist/js/adminlte.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('dist/js/pages/dashboard.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('dist/js/demo.js') }}"></script>


<!-- DataTables -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>

<!-- Light gallery -->


<script src="{{ asset('dist/js/lightbox.js') }}"></script>
<!-- page script -->

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<!-- AdminLTE App -->
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });

  });
</script>