routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login ');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('offices', 'OfficesController');
Route::resource('users', 'UsersController');
Route::resource('files', 'FilesController');
Route::get('files/{id}email', 'FilesController@email');
Route::resource('online', 'OnlineController');
Route::resource('calculations', 'CalculationsController');
Route::resource('expedientes', 'ExpedienteController');

Route::resource('calculadora', 'CalculadoraController');
Route::post('calculadora', 'CalculadoraController@calculo')->name('calculo.post');


Route::get('mapa', function () {
    return view('formulario.mapa ');
});

Route::resource('directorio', 'DirectorioController');

Route::resource('sucursales', 'SucursalesController');
Route::post('sucursales', 'SucursalesController@sucursal')->name('sucursal.post');

app/Office.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Office extends Model
{

    public $timestamps = false;
    //
    protected $fillable = [
            'nombre_suc',
            'email_suc',
            'codigo',
            'calle',
            'numInt',
            'numExt',
            'colonia',
            'municipio',
            'estado',
            'cp',
            'telefono_suc',
            'lat',
            'lng',
            'img_ciudad',
            'img_suc',
            'descripcion_suc',
            'fecha_ini',
            'fecha_mod'
    ];
}

app/Http/Controllers/OfficesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Office;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class OfficesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        $idUser = Auth::User()->id;

        $idSucursal = DB::select('SELECT idSucursal, idRol FROM controls WHERE idUser = ?', [$idUser]);
        $idRol = $idSucursal[0]->idRol;
        $idSuc = $idSucursal[0]->idSucursal;





        if ($idRol == 1 || $idRol == 2 || $idRol == 3){

            $offices = DB::table('offices')
                    ->leftJoin('controls', 'offices.id', '=', 'controls.idSucursal')
                    ->where('controls.idUser', '=', $idUser)
                    ->get();

         }

        if ($idRol == 4 || $idRol == 5){
            $offices = Office::get();

        }


        return view('offices.index', compact('offices', 'idRol'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('offices.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        return $request['img_ciudad'];


        if($request->hasFile('img_ciudad')){


            $fileCiudad = $request->file('img_ciudad');
            $imgCiudad = time().$fileCiudad->getClientOriginalName();

            $fileCiudad->move(public_path().'/img/sucursales/', $imgCiudad);

        }else{

            $imgCiudad = 'sinimagen.jpg';
        }

        if($request->hasFile('img_suc')){

            return 'entro';
            $fileSuc = $request->file('img_suc');
            $imgSuc = time().$fileSuc->getClientOriginalName();

            $fileSuc->move(public_path().'/img/sucursales/', $imgSuc);

        }else{
            $imgSuc = 'sinsuc.jpg';
        }

        Office::create([
            'nombre_suc' => request('nombre_suc'),
            'email_suc' => request('email_suc'),
            'codigo'=> request('codigo'),
            'calle'=> request('calle'),
            'numInt'=> request('numInt'),
            'numExt'=> request('numExt'),
            'colonia'=> request('colonia'),
            'municipio'=> request('municipio'),
            'estado'=> request('estado'),
            'cp'=> request('cp'),
            'telefono_suc'=> request('telefono_suc'),
            'lat'=> request('lat'),
            'lng'=> request('lng'),
            'img_ciudad' => $imgCiudad,
            'img_suc' => $imgSuc,
            'descripcion_suc' => request('descripcion_suc')
        ]);

        return redirect('/offices');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $sucursales = DB::table('offices')
        ->where('nombre_suc', '=', $id)
        ->get();

        return view('offices.show', compact('sucursales'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {


        $office = Office::findOrFail($id);




        return view('offices.edit', compact('office'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $office = Office::findOrFail($id);

       DB::table('offices')
       ->where('id', $id)
       ->update([
       'nombre_suc' => request('nombre_suc'),
       'email_suc' => request('email_suc'),
       'codigo'=> request('codigo'),
       'calle'=> request('calle'),
       'numInt'=> request('numInt'),
       'numExt'=> request('numExt'),
       'colonia'=> request('colonia'),
       'municipio'=> request('municipio'),
       'estado'=> request('estado'),
       'cp'=> request('cp'),
       'telefono_suc'=> request('telefono_suc'),
       'lat'=> request('lat'),
       'lng'=> request('lng'),
       'img_ciudad' => 'img_ciudad',
       'img_suc' => 'img_suc',
       'descripcion_suc' => request('descripcion_suc')
       ]);


      return  redirect('/offices');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/offices/create.blade.php
@extends('layouts.admin')



@section('content')

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark"> Nueva Sucursal</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ url('home') }}">Home</a></li>
          <li class="breadcrumb-item"><a href="{{ url('sucursales') }}">Sucursales</a></li>
            <li class="breadcrumb-item active"> Nueva Sucursal</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>


  <div class="card card-info">
    <div class="card-header">
      <h3 class="card-title">Ingresa los datos</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="{{ url('offices') }}" method="post">

      <div class="card-body">
        @csrf
       <div class="row">
        <div class="form-group col-md-3">
            <label for="nombre">Nombre de sucursal</label>
            <input type="text" name="nombre_suc" required class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="email">Email Sucursal</label>
            <input type="email" name="email_suc" required class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="password">Código Sucursal</label>
            <input type="text" name="codigo" required class="form-control">
        </div>
        <div class="form-group col-md-3">
            <label for="calle">Calle</label>
            <input type="text" name="calle"  class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="password">Numero Ext</label>
            <input type="text" name="numExt"  class="form-control">
        </div>
      </div>
      <div class="row">

        <div class="form-group col-md-1">
            <label for="password">Num Interior</label>
            <input type="text" name="numInt"  class="form-control">
        </div>

        <div class="form-group col-md-2">
            <label for="password">Colonia</label>
            <input type="text" name="colonia"  class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="password">Municipio</label>
            <input type="text" name="municipio"  class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="password">Estado</label>
            <input type="text" name="estado"  class="form-control">
        </div>
        <div class="form-group col-md-1">
            <label for="password">CP</label>
            <input type="text" name="cp"  class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="password">Teléfono</label>
            <input type="text" name="telefono_suc"  class="form-control">
        </div>
        <div class="form-group col-md-1">
            <label for="password">Lat</label>
            <input type="text" name="lat"  class="form-control">
        </div>
        <div class="form-group col-md-1">
            <label for="password">Lng</label>
            <input type="text" name="lng"  class="form-control">
        </div>
      </div>
      <div class="row">
        <div class="col-md-6"> <br>
          <p>Ciudad</p>
          <div class="custom-file">
            <input type="file" class="custom-file-input" id="customFile" name="img_ciudad" >
            <label class="custom-file-label" for="customFile" >Seleccionar archivo</label>
          </div>
        </div>
        <div class="col-md-6"> <br>
          <p>Sucursal</p>
          <div class="custom-file">
            <input type="file" class="custom-file-input" id="customFile1" name="img_suc" >
            <label class="custom-file-label" for="customFile">Seleccionar archivo</label>
          </div>
        </div>

          </div>
      </div>
      <div class="row">
          <div class="form-group col-md-8 ">
            <input class="form-control" type="text" name="descripcion_suc" id="">
          </div>
      </div>

      </div>
      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Enviar</button>
      </div>
      <!-- /.card-body -->

    </form>


  </div>
  <!-- /.card -->


  <div id="map"></div>
@endsection


<script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD74Y8NCL6W0xEGVZvgGjUIZ4UYHz8ZXQM&callback=initMap&libraries=&v=weekly"
      defer
    ></script>
<style type="text/css">
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 30%;
        width: 30%;

      }



      #floating-panel {

        top: 10px;
        left: 25%;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: "Roboto", "sans-serif";
        line-height: 30px;
        padding-left: 10px;
      }
    </style>

    <script>
      function initMap() {
  var map = new google.maps.Map(document.getElementById("map"), {
    zoom: 12,
    center: { lat: 19.34, lng: -99.644 }
  });
  var geocoder = new google.maps.Geocoder();

  document.getElementById("submit1").addEventListener("click", function() {
    geocodeAddress(geocoder, map);
  });
}

function geocodeAddress(geocoder, resultsMap) {
  var address = document.getElementById("address").value;
  geocoder.geocode({ address: address }, function(results, status) {
    if (status === "OK") {
      resultsMap.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
        map: resultsMap,
        position: results[0].geometry.location

      });
      console.log(results);
      console.log(results[0].geometry.location.lat);
      console.log(results[0].geometry.location.lng);
    } else {
      alert("Geocode was not successful for the following reason: " + status);
    }
  });
}
    </script>

resources/views/offices/delete.blade.php
<form action="{{ route('offices.destroy', $office->id )}}" method="POST" style="display:inline-block;">
    @method('DELETE')
    @csrf
    <button type="submit" class="btn btn-danger">Eliminar</button>
</form>

resources/views/offices/edit.blade.php
@extends('layouts.admin')



@section('content')

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Editar Sucursal</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ url('home') }}">Home</a></li>
          <li class="breadcrumb-item"><a href="{{ url('sucursales') }}">Sucursales</a></li>
            <li class="breadcrumb-item active"> Nueva Sucursal</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>


  <div class="card card-info">
    <div class="card-header">
      <h3 class="card-title">Ingresa los datos</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="{{ route('offices.update',  $office->id) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PUT')
      <div class="card-body">

       <div class="row">
        <div class="form-group col-md-3">
            <label for="nombre">Nombre de sucursal</label>
            <input type="text" name="nombre_suc" value="{{ $office->nombre_suc }}" class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="email">Email Sucursal</label>
            <input type="email" name="email_suc" value="{{ $office->email_suc }}" class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="password">Código Sucursal</label>
            <input type="text" name="codigo" value="{{ $office->codigo }}" class="form-control">
        </div>
        <div class="form-group col-md-3">
            <label for="calle">Calle</label>
            <input type="text" name="calle" value="{{ $office->calle }}" class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="password">Numero Ext</label>
            <input type="text" name="numExt" value="{{ $office->numExt }}" class="form-control">
        </div>
      </div>
      <div class="row">

        <div class="form-group col-md-1">
            <label for="password">Num Interior</label>
            <input type="text" name="numInt" value="{{ $office->numInt }}" class="form-control">
        </div>

        <div class="form-group col-md-2">
            <label for="password">Colonia</label>
            <input type="text" name="colonia" value="{{ $office->colonia }}" class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="password">Municipio</label>
            <input type="text" name="municipio" value="{{ $office->municipio }}" class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="password">Estado</label>
            <input type="text" name="estado" value="{{ $office->estado }}" class="form-control">
        </div>
        <div class="form-group col-md-1">
            <label for="password">CP</label>
            <input type="text" name="cp" value="{{ $office->cp }}" class="form-control">
        </div>
        <div class="form-group col-md-2">
            <label for="password">Teléfono</label>
            <input type="text" name="telefono_suc" value="{{ $office->telefono_suc }}" class="form-control">
        </div>
        <div class="form-group col-md-1">
            <label for="password">Lat</label>
            <input type="text" name="lat" value="{{ $office->lat }}" class="form-control">
        </div>
        <div class="form-group col-md-1">
            <label for="password">Lng</label>
            <input type="text" name="lng" value="{{ $office->lng }}"  class="form-control">
        </div>
      </div>
      <div class="row">
        <div class="col-md-6"> <br>
          <p>Ciudad</p>
          <div class="custom-file">
            <input type="file" class="custom-file-input" id="customFile" name="img_ciudad" >
            <label class="custom-file-label" for="customFile" >Seleccionar archivo</label>
          </div>
        </div>
        <div class="col-md-6"> <br>
          <p>Sucursal</p>
          <div class="custom-file">
            <input type="file" class="custom-file-input" id="customFile1" name="img_suc" >
            <label class="custom-file-label" for="customFile">Seleccionar archivo</label>
          </div>
        </div>

          </div>
      </div>
      <div class="row">
          <div class="form-group col-md-8 ">
            <input class="form-control" type="text" name="descripcion_suc" value="{{ $office->descripcion_suc }}">
          </div>
      </div>

      </div>
      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Actualizar</button>
      </div>
      <!-- /.card-body -->

    </form>


  </div>
  <!-- /.card -->


  <div id="map"></div>
@endsection


<script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD74Y8NCL6W0xEGVZvgGjUIZ4UYHz8ZXQM&callback=initMap&libraries=&v=weekly"
      defer
    ></script>
<style type="text/css">
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 30%;
        width: 30%;

      }



      #floating-panel {

        top: 10px;
        left: 25%;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: "Roboto", "sans-serif";
        line-height: 30px;
        padding-left: 10px;
      }
    </style>

    <script>
      function initMap() {
  var map = new google.maps.Map(document.getElementById("map"), {
    zoom: 12,
    center: { lat: 19.34, lng: -99.644 }
  });
  var geocoder = new google.maps.Geocoder();

  document.getElementById("submit1").addEventListener("click", function() {
    geocodeAddress(geocoder, map);
  });
}

function geocodeAddress(geocoder, resultsMap) {
  var address = document.getElementById("address").value;
  geocoder.geocode({ address: address }, function(results, status) {
    if (status === "OK") {
      resultsMap.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
        map: resultsMap,
        position: results[0].geometry.location

      });
      console.log(results);
      console.log(results[0].geometry.location.lat);
      console.log(results[0].geometry.location.lng);
    } else {
      alert("Geocode was not successful for the following reason: " + status);
    }
  });
}
    </script>

resources/views/offices/index.blade.php
@extends('layouts.admin')


@section('content')

<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Sucursales</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ url('home') }}">Home</a></li>
            <li class="breadcrumb-item active">Sucursales</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>

<div class="container-fluid spark-screen">
    <div class="row">
        <div class="col-md-12 ">

            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">

                    <div class="box-tools pull-right " >


                      @switch($idRol)
                          @case(4)
                          <a href=" {{ url('offices/create') }} " class="btn btn-success">Nueva Sucursal</a>
                              @break
                          @case(5)
                          <a href=" {{ url('offices/create') }} " class="btn btn-success">Nueva Sucursal</a>
                              @break
                          @default

                      @endswitch
                  </div>

                </div>
                <div class="box-body">

                  <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <th>Nombre</th>
                            <th>Email</th>
                            <th>Código</th>
                            <th>Acciones</th>
                        </thead>
                        <tbody>
                            @foreach ($offices as $office )
                                <tr>
                                <td>{{ $office->nombre_suc }}</td>
                                <td>{{ $office->email_suc }}</td>
                                <td>{{ $office->codigo }}</td>
                                <td>


                                  @if ($idRol == 2 || $idRol == 1)
                                  <a href="{{ route('sucursales.show', $office->nombre_suc) }}" class="btn btn-primary">Ver</a>
                                  @endif
                                  @if ($idRol == 3)
                                  <a href="{{ route('sucursales.show', $office->nombre_suc) }}" class="btn btn-primary">Ver</a>
                                  <a href="{{ route('offices.edit', $office->id) }}" class="btn btn-primary">Editar</a>
                                  @endif
                                  @if ($idRol == 4 ||  $idRol == 5)
                                  <a href="{{ route('sucursales.show', $office->nombre_suc) }}" class="btn btn-primary">Ver</a>
                                  <a href="{{ route('offices.edit', $office->id) }}" class="btn btn-primary">Editar</a>
                                  @include('offices.delete', ['office'=>$office])
                                  @endif



                                </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
    </div>
</div>

@endsection

resources/views/offices/show.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Calculadora ISR</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <!-- Tempusdominus Bbootstrap 4 -->
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<meta name="csrf-token" content="{{ csrf_token() }}" />
</head>
<body>
 
    <div class="container">
    
        <div class="row">
            <div class="col-sm-4">
                
            </div>    
        </div>    

</body>
</html>    